const productos = [
    {
        id: 1,
        nombre: "Tarta de frutilla", 
        precio: 9000,
        info: "Base de tarta con crema chantilly y frutillas. (14 porciones aprox)",
        img: "../img/tienA.webp",
        cantidad: 1,
    },
    { 
        id: 2,
        nombre: "Cookie box", 
        precio: 3500,
        info: "Galletitas de Maicena surtidas. Chocolate, vainilla, cubiertas con glase o azucar implapable. (Caja de 300gr.)",
        img: "../img/tienB.webp",
        cantidad: 1,
    },
    { 
        id: 3,
        nombre: "Cheesecake de arandanos", 
        precio: 8200,
        info: "Base de galletitas de vainilla, queso crema. Decorado con arandanos. (10 porciones aprox)",
        img: "../img/tienC.webp",
        cantidad: 1,
    },
    { 
        id: 4,
        nombre: "Torta Koala", 
        precio: 9000,
        info: "Bizcochuelo de chocolate amargo cubierto con crema chantilly de chocolate y decorado con una cara de Koala. (8 porciones aprox)",
        img: "../img/tienD.webp",
        cantidad: 1,
    },
    { 
        id: 5,
        nombre: "Pasion de chocolate", 
        precio: 10000,
        info: "Bizcochuelo de chocolate, dulce de leche. Cobertura de ganache de chocolate. (10 porciones aprox)",
        img: "../img/tienE.webp",
        cantidad: 1,
    },
    { 
        id: 6,
        nombre: "OREO Cheesecake", 
        precio: 8000,
        info: "Queso crema, galletitas OREOS. (8 porciones aprox)",
        img: "../img/tienF.webp",
        cantidad: 1,
    },
    { 
        id: 7,
        nombre: "Budin de pistachos", 
        precio: 4700,
        info: "Budin de vainilla con pistachos. Decorado con glase real y pistachos picados.",
        img: "../img/tienG.webp",
        cantidad: 1,
    },
    { 
        id: 8,
        nombre: "Tarde de moras", 
        precio: 7000,
        info: "Bizcochuelo de vainilla, mermelada de moras. Decorada con crema chantilly y moras. (10 porciones aprox)",
        img: "../img/44.webp",
        cantidad: 1,
    },
    { 
        id: 9,
        nombre: "Selva negra", 
        precio: 8400,
        info: "Bizcochuelo de Chocolate, crema chantilly y cerezas.(8 porciones aprox)",
        img: "../img/tienI.webp",
        cantidad: 1,
    },
    { 
        id: 10,
        nombre: "Angel Cake", 
        precio: 4600,
        info: "Torta esponjosa de limon, decorada con una capa de glaseado de limón.",
        img: "../img/tienJ.webp",
        cantidad: 1,
    },
    { 
        id: 11,
        nombre: "Budin de chocolate", 
        precio: 5000,
        info: "Budin de chocolate amargo bañado en chocolate.",
        img: "../img/budiB.webp",
        cantidad: 1,
    },
    { 
        id: 12,
        nombre: "Torta brownie", 
        precio: 8000,
        info: "Brownie con nueces, dulce de leche. Decorada con merengue italiano y galletitas de chocolate con forma de ositos. (6 porciones aprox)",
        img: "../img/46.webp",
        cantidad: 1,
    },
];